# Generated by Django 5.0.7 on 2024-07-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='distance',
        ),
    ]
